INFO:     Will watch for changes in these directories: ['/Users/stevencohen/Projects/universal_recycling/orders_project/backend']
INFO:     Uvicorn running on http://0.0.0.0:8004 (Press CTRL+C to quit)
INFO:     Started reloader process [32717] using StatReload
INFO:     Started server process [32786]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     127.0.0.1:56301 - "POST /orders/receive HTTP/1.1" 200 OK
INFO:     127.0.0.1:56427 - "GET /orders/pending_orders HTTP/1.1" 200 OK
INFO:     127.0.0.1:56427 - "GET /static/css/style.css HTTP/1.1" 200 OK
INFO:     127.0.0.1:56428 - "GET /static/js/pending_orders.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:56428 - "GET /static/js/components/shared_filters.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:56427 - "GET /static/js/components/pdf_modal.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:56431 - "GET /static/js/components/expand_line_items.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:56432 - "GET /static/js/components/attachment_modal.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:56434 - "GET /static/js/components/receive_modal.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:56436 - "GET /static/js/components/order_note_modal.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:56436 - "GET /lookups/requesters HTTP/1.1" 200 OK
INFO:     127.0.0.1:56434 - "GET /lookups/suppliers HTTP/1.1" 200 OK
INFO:     127.0.0.1:56434 - "GET /orders/api/orders/pending_orders HTTP/1.1" 200 OK
INFO:     127.0.0.1:56434 - "GET /orders/api/items_for_order/83 HTTP/1.1" 200 OK
INFO:     127.0.0.1:56434 - "POST /orders/receive HTTP/1.1" 200 OK
INFO:     127.0.0.1:56434 - "GET /orders/pending_orders HTTP/1.1" 200 OK
INFO:     127.0.0.1:56434 - "GET /static/css/style.css HTTP/1.1" 200 OK
INFO:     127.0.0.1:56474 - "GET /static/js/pending_orders.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:56434 - "GET /static/js/components/expand_line_items.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:56481 - "GET /static/js/components/receive_modal.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:56478 - "GET /static/js/components/order_note_modal.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:56482 - "GET /static/js/components/pdf_modal.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:56474 - "GET /static/js/components/shared_filters.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:56477 - "GET /static/js/components/attachment_modal.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:56477 - "GET /lookups/suppliers HTTP/1.1" 200 OK
INFO:     127.0.0.1:56474 - "GET /lookups/requesters HTTP/1.1" 200 OK
INFO:     127.0.0.1:56474 - "GET /orders/api/orders/pending_orders HTTP/1.1" 200 OK
INFO:     127.0.0.1:56474 - "GET /orders/new HTTP/1.1" 200 OK
INFO:     127.0.0.1:56474 - "GET /lookups/requesters HTTP/1.1" 200 OK
INFO:     127.0.0.1:56474 - "GET /lookups/suppliers HTTP/1.1" 200 OK
INFO:     127.0.0.1:56474 - "GET /lookups/items HTTP/1.1" 200 OK
INFO:     127.0.0.1:56474 - "GET /lookups/projects HTTP/1.1" 200 OK
INFO:     127.0.0.1:56474 - "GET /lookups/settings HTTP/1.1" 200 OK
INFO:     127.0.0.1:56554 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:56554 - "GET /static/js/login.js HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:56554 - "GET /favicon.ico HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.scope, self.receive, self.send
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/starlette/middleware/sessions.py", line 85, in __call__
    await self.app(scope, receive, send_wrapper)
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/starlette/routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/starlette/routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/fastapi/routing.py", line 338, in app
    response = actual_response_class(content, **response_args)
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/starlette/responses.py", line 313, in __init__
    media_type = guess_type(filename or path)[0] or "text/plain"
                 ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.2/Frameworks/Python.framework/Versions/3.13/lib/python3.13/mimetypes.py", line 322, in guess_type
    return _db.guess_type(url, strict)
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.2/Frameworks/Python.framework/Versions/3.13/lib/python3.13/mimetypes.py", line 123, in guess_type
    url = os.fspath(url)
TypeError: expected str, bytes or os.PathLike object, not list
INFO:     127.0.0.1:56555 - "POST /login HTTP/1.1" 200 OK
INFO:     127.0.0.1:56555 - "GET /home HTTP/1.1" 200 OK
INFO:     127.0.0.1:56555 - "GET /favicon.ico HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.scope, self.receive, self.send
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/starlette/middleware/sessions.py", line 85, in __call__
    await self.app(scope, receive, send_wrapper)
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/starlette/routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/starlette/routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/fastapi/routing.py", line 338, in app
    response = actual_response_class(content, **response_args)
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/starlette/responses.py", line 313, in __init__
    media_type = guess_type(filename or path)[0] or "text/plain"
                 ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.2/Frameworks/Python.framework/Versions/3.13/lib/python3.13/mimetypes.py", line 322, in guess_type
    return _db.guess_type(url, strict)
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.2/Frameworks/Python.framework/Versions/3.13/lib/python3.13/mimetypes.py", line 123, in guess_type
    url = os.fspath(url)
TypeError: expected str, bytes or os.PathLike object, not list
INFO:     127.0.0.1:56568 - "GET /orders/new HTTP/1.1" 200 OK
INFO:     127.0.0.1:56568 - "GET /lookups/requesters HTTP/1.1" 200 OK
INFO:     127.0.0.1:56568 - "GET /lookups/suppliers HTTP/1.1" 200 OK
INFO:     127.0.0.1:56568 - "GET /lookups/items HTTP/1.1" 200 OK
INFO:     127.0.0.1:56568 - "GET /lookups/projects HTTP/1.1" 200 OK
INFO:     127.0.0.1:56568 - "GET /lookups/settings HTTP/1.1" 200 OK
INFO:     127.0.0.1:56570 - "GET /lookups/suppliers HTTP/1.1" 200 OK
INFO:     127.0.0.1:56570 - "POST /orders/api/generate_pdf HTTP/1.1" 200 OK
INFO:     127.0.0.1:56585 - "POST /lookups/orders/ HTTP/1.1" 307 Temporary Redirect
INFO:     127.0.0.1:56585 - "POST /lookups/orders HTTP/1.1" 200 OK
INFO:     127.0.0.1:56585 - "GET /lookups/settings HTTP/1.1" 200 OK
INFO:     127.0.0.1:56585 - "GET /orders/pending_orders HTTP/1.1" 200 OK
INFO:     127.0.0.1:56585 - "GET /lookups/requesters HTTP/1.1" 200 OK
INFO:     127.0.0.1:56598 - "GET /lookups/suppliers HTTP/1.1" 200 OK
INFO:     127.0.0.1:56598 - "GET /orders/api/orders/pending_orders HTTP/1.1" 200 OK
INFO:     127.0.0.1:56598 - "GET /orders/api/items_for_order/84 HTTP/1.1" 200 OK
INFO:     127.0.0.1:56598 - "GET /orders/attachments/84 HTTP/1.1" 200 OK
INFO:     127.0.0.1:56598 - "GET /orders/attachments/84 HTTP/1.1" 200 OK
INFO:     127.0.0.1:56598 - "POST /orders/upload_attachment HTTP/1.1" 200 OK
INFO:     127.0.0.1:56598 - "GET /orders/attachments/84 HTTP/1.1" 200 OK
INFO:     127.0.0.1:56598 - "GET /orders/attachments/84 HTTP/1.1" 200 OK
INFO:     127.0.0.1:56598 - "GET /orders/attachments/84 HTTP/1.1" 200 OK
INFO:     127.0.0.1:56598 - "GET /data/uploads/84_Amsterdam_Cheese_Company.pdf HTTP/1.1" 200 OK
INFO:     127.0.0.1:56605 - "GET /orders/api/items_for_order/84 HTTP/1.1" 200 OK
INFO:     127.0.0.1:56618 - "POST /orders/receive HTTP/1.1" 200 OK
INFO:     127.0.0.1:56618 - "GET /orders/pending_orders HTTP/1.1" 200 OK
INFO:     127.0.0.1:56618 - "GET /lookups/requesters HTTP/1.1" 200 OK
INFO:     127.0.0.1:56620 - "GET /lookups/suppliers HTTP/1.1" 200 OK
INFO:     127.0.0.1:56620 - "GET /orders/api/orders/pending_orders HTTP/1.1" 200 OK
INFO:     127.0.0.1:56620 - "GET /orders/new HTTP/1.1" 200 OK
INFO:     127.0.0.1:56620 - "GET /lookups/requesters HTTP/1.1" 200 OK
INFO:     127.0.0.1:56620 - "GET /lookups/suppliers HTTP/1.1" 200 OK
INFO:     127.0.0.1:56620 - "GET /lookups/items HTTP/1.1" 200 OK
INFO:     127.0.0.1:56620 - "GET /lookups/projects HTTP/1.1" 200 OK
INFO:     127.0.0.1:56620 - "GET /lookups/settings HTTP/1.1" 200 OK
INFO:     127.0.0.1:56639 - "POST /lookups/orders/ HTTP/1.1" 307 Temporary Redirect
INFO:     127.0.0.1:56639 - "POST /lookups/orders HTTP/1.1" 200 OK
INFO:     127.0.0.1:56639 - "GET /lookups/settings HTTP/1.1" 200 OK
INFO:     127.0.0.1:56639 - "GET /orders/received_orders HTTP/1.1" 200 OK
INFO:     127.0.0.1:56639 - "GET /lookups/requesters HTTP/1.1" 200 OK
INFO:     127.0.0.1:56639 - "GET /lookups/suppliers HTTP/1.1" 200 OK
INFO:     127.0.0.1:56639 - "GET /orders/api/received_orders HTTP/1.1" 200 OK
INFO:     127.0.0.1:56639 - "GET /orders/pending_orders HTTP/1.1" 200 OK
INFO:     127.0.0.1:56639 - "GET /lookups/requesters HTTP/1.1" 200 OK
INFO:     127.0.0.1:56652 - "GET /lookups/suppliers HTTP/1.1" 200 OK
INFO:     127.0.0.1:56652 - "GET /orders/api/orders/pending_orders HTTP/1.1" 200 OK
INFO:     127.0.0.1:56654 - "GET /orders/api/items_for_order/85 HTTP/1.1" 200 OK
INFO:     127.0.0.1:56656 - "POST /orders/receive HTTP/1.1" 200 OK
INFO:     127.0.0.1:56656 - "GET /orders/pending_orders HTTP/1.1" 200 OK
INFO:     127.0.0.1:56656 - "GET /lookups/requesters HTTP/1.1" 200 OK
INFO:     127.0.0.1:56667 - "GET /lookups/suppliers HTTP/1.1" 200 OK
INFO:     127.0.0.1:56667 - "GET /orders/api/orders/pending_orders HTTP/1.1" 200 OK
INFO:     127.0.0.1:56672 - "GET /orders/audit_trail HTTP/1.1" 200 OK
INFO:     127.0.0.1:56672 - "GET /lookups/suppliers HTTP/1.1" 200 OK
INFO:     127.0.0.1:56672 - "GET /lookups/requesters HTTP/1.1" 200 OK
INFO:     127.0.0.1:56674 - "GET /favicon.ico HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.scope, self.receive, self.send
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/starlette/middleware/sessions.py", line 85, in __call__
    await self.app(scope, receive, send_wrapper)
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/starlette/routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/starlette/routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/fastapi/routing.py", line 338, in app
    response = actual_response_class(content, **response_args)
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/starlette/responses.py", line 313, in __init__
    media_type = guess_type(filename or path)[0] or "text/plain"
                 ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.2/Frameworks/Python.framework/Versions/3.13/lib/python3.13/mimetypes.py", line 322, in guess_type
    return _db.guess_type(url, strict)
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.2/Frameworks/Python.framework/Versions/3.13/lib/python3.13/mimetypes.py", line 123, in guess_type
    url = os.fspath(url)
TypeError: expected str, bytes or os.PathLike object, not list
INFO:     127.0.0.1:56672 - "GET /orders/api/audit_trail HTTP/1.1" 200 OK
INFO:     127.0.0.1:56676 - "GET /orders/api/items_for_order/85 HTTP/1.1" 200 OK
INFO:     127.0.0.1:56679 - "GET /orders/api/audit_trail HTTP/1.1" 200 OK
INFO:     127.0.0.1:56694 - "GET /orders/api/audit_trail HTTP/1.1" 200 OK
INFO:     127.0.0.1:56715 - "GET /orders/audit_trail HTTP/1.1" 200 OK
INFO:     127.0.0.1:56715 - "GET /lookups/suppliers HTTP/1.1" 200 OK
INFO:     127.0.0.1:56717 - "GET /lookups/requesters HTTP/1.1" 200 OK
INFO:     127.0.0.1:56719 - "GET /favicon.ico HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.scope, self.receive, self.send
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/starlette/middleware/sessions.py", line 85, in __call__
    await self.app(scope, receive, send_wrapper)
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/starlette/routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/starlette/routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/fastapi/routing.py", line 338, in app
    response = actual_response_class(content, **response_args)
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/starlette/responses.py", line 313, in __init__
    media_type = guess_type(filename or path)[0] or "text/plain"
                 ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.2/Frameworks/Python.framework/Versions/3.13/lib/python3.13/mimetypes.py", line 322, in guess_type
    return _db.guess_type(url, strict)
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.2/Frameworks/Python.framework/Versions/3.13/lib/python3.13/mimetypes.py", line 123, in guess_type
    url = os.fspath(url)
TypeError: expected str, bytes or os.PathLike object, not list
INFO:     127.0.0.1:56717 - "GET /orders/api/audit_trail HTTP/1.1" 200 OK
INFO:     127.0.0.1:56717 - "GET /maintenance HTTP/1.1" 200 OK
INFO:     127.0.0.1:56717 - "GET /lookups/users HTTP/1.1" 200 OK
INFO:     127.0.0.1:56715 - "GET /lookups/requesters HTTP/1.1" 200 OK
INFO:     127.0.0.1:56721 - "GET /lookups/items HTTP/1.1" 200 OK
INFO:     127.0.0.1:56724 - "GET /lookups/projects HTTP/1.1" 200 OK
INFO:     127.0.0.1:56726 - "GET /lookups/settings HTTP/1.1" 200 OK
INFO:     127.0.0.1:56727 - "GET /lookups/business_details HTTP/1.1" 200 OK
INFO:     127.0.0.1:56726 - "GET /favicon.ico HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.scope, self.receive, self.send
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/starlette/middleware/sessions.py", line 85, in __call__
    await self.app(scope, receive, send_wrapper)
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/starlette/routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/starlette/routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/fastapi/routing.py", line 338, in app
    response = actual_response_class(content, **response_args)
  File "/Users/stevencohen/Projects/universal_recycling/orders_project/venv/lib/python3.13/site-packages/starlette/responses.py", line 313, in __init__
    media_type = guess_type(filename or path)[0] or "text/plain"
                 ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.2/Frameworks/Python.framework/Versions/3.13/lib/python3.13/mimetypes.py", line 322, in guess_type
    return _db.guess_type(url, strict)
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.2/Frameworks/Python.framework/Versions/3.13/lib/python3.13/mimetypes.py", line 123, in guess_type
    url = os.fspath(url)
TypeError: expected str, bytes or os.PathLike object, not list
INFO:     127.0.0.1:56730 - "GET /orders/pending_orders HTTP/1.1" 200 OK
INFO:     127.0.0.1:56730 - "GET /lookups/requesters HTTP/1.1" 200 OK
INFO:     127.0.0.1:56732 - "GET /lookups/suppliers HTTP/1.1" 200 OK
INFO:     127.0.0.1:56732 - "GET /orders/api/orders/pending_orders HTTP/1.1" 200 OK
INFO:     127.0.0.1:56734 - "GET /orders/api/orders/pending_orders?requester=Raymond HTTP/1.1" 200 OK
INFO:     127.0.0.1:56736 - "GET /orders/api/generate_pdf_for_order/85 HTTP/1.1" 200 OK
